global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'concrete-monitor'

scrape_configs:
  - job_name: 'concrete-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']